# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

name: ensemble_forecast_download

jobs:
  gfs_seamless:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
    container: rqthomas/vera-rocker:latest
    steps:
      - uses: actions/checkout@v3

      - name: Download
        shell: Rscript {0}
        run: |
          source("drivers/ensemble_forecasts.R")

      - name: Healthcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -m 10 --retry 5 https://hc-ping.com/09ad92fc-a41c-496d-96c2-94974dc2dfdb
